on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        
      - name: Build NuttyOS
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.4
          target: esp32s3
          path: "NuttyOS"
          command: idf.py build merge-bin

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: NuttyOS Binary
          path: NuttyOS/build/merged-binary.bin