on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Get ESP-IDF version
        id: idf_version
        uses: mikefarah/yq@v4.53.2
        with:
          cmd: yq e '.dependencies.idf.version' NuttyOS/dependencies.lock

      - name: Calculate binary name
        id: bin_name
        run: |
          COMMIT_SHA="${{ github.event.pull_request.head.sha || github.sha }}"

          # Shorten the SHA to 7 chars
          COMMIT_SHA=${COMMIT_SHA:0:7}

          echo "BIN_NAME=nuttyos-${COMMIT_SHA}.bin" >> $GITHUB_OUTPUT

      - name: Cache managed components
        uses: actions/cache@v4
        with:
          path: NuttyOS/managed_components
          key: managed-components-${{ hashFiles('NuttyOS/dependencies.lock') }}
          restore-keys: |
            managed-components-

      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: NuttyOS/build
          key: esp-idf-build-${{ hashFiles('NuttyOS/**.[ch]', 'NuttyOS/sdkconfig', 'NuttyOS/dependencies.lock') }}
          restore-keys: |
            esp-idf-build-

      - name: Build NuttyOS
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v${{ steps.idf_version.outputs.result }}
          target: esp32s3
          path: "NuttyOS"
          command: idf.py build merge-bin -o ${{ steps.bin_name.outputs.BIN_NAME }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          path: NuttyOS/build/${{ steps.bin_name.outputs.BIN_NAME }}
          archive: false